targetScope = 'resourceGroup'

param location string
param logAnalyticsWorkspaceName string
param applicationInsightsName string
param grafanaName string
param grafanaAdminPrincipalId string

resource logAnalytics 'Microsoft.OperationalInsights/workspaces@2022-10-01' = {
  name: logAnalyticsWorkspaceName
  location: location
  properties: {
    sku: {
      name: 'PerGB2018'
    }
    retentionInDays: 30
    features: {
      enableLogAccessUsingOnlyResourcePermissions: true
    }
  }
}

resource applicationInsights 'Microsoft.Insights/components@2020-02-02' = {
  name: applicationInsightsName
  location: location
  kind: 'web'
  properties: {
    Application_Type: 'web'
    Flow_Type: 'Bluefield'
    IngestionMode: 'LogAnalytics'
    WorkspaceResourceId: logAnalytics.id
    RetentionInDays: 90
  }
}

resource grafana 'Microsoft.Dashboard/grafana@2023-09-01' = {
  name: grafanaName
  location: location
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    autoGeneratedDomainNameLabelScope: 'TenantReuse'
    deterministicOutboundIP: 'Disabled'
    publicNetworkAccess: 'Enabled'
    zoneRedundancy: 'Disabled'
  }
  sku: {
    name: 'Standard'
  }
}

var monitoringReaderRoleId = subscriptionResourceId(
  'Microsoft.Authorization/roleDefinitions',
  '43d0d8ad-25c7-4714-9337-8ba259a9fe05'
)

resource grafanaMonitoringReader 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(resourceGroup().id, grafana.id, monitoringReaderRoleId)
  properties: {
    principalId: grafana.identity.principalId
    principalType: 'ServicePrincipal'
    roleDefinitionId: monitoringReaderRoleId
  }
}

var grafanaAdminRoleId = subscriptionResourceId(
  'Microsoft.Authorization/roleDefinitions',
  '22926164-76b3-42b3-bc55-97df8dab3e41'
)

resource grafanaAdmin 'Microsoft.Authorization/roleAssignments@2022-04-01' = if (!empty(grafanaAdminPrincipalId)) {
  name: guid(grafana.id, grafanaAdminPrincipalId, grafanaAdminRoleId)
  scope: grafana
  properties: {
    principalId: grafanaAdminPrincipalId
    roleDefinitionId: grafanaAdminRoleId
  }
}

output logAnalyticsWorkspaceId string = logAnalytics.id
output applicationInsightsId string = applicationInsights.id
output applicationInsightsAppId string = applicationInsights.properties.AppId
output grafanaId string = grafana.id
output grafanaName string = grafana.name
output grafanaEndpoint string = grafana.properties.endpoint
